// <auto-generated />
namespace HRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig071 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig071));
        
        string IMigrationMetadata.Id
        {
            get { return "201904261006419_mig071"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
